### ISSUE TITLE
How does one handle an array of inputs?

### ISSUE THREAD

**Issue by fwgreen** [Macro-swift/MacroExpress#4]
Thanks for putting this project out there!  I love its straightforward nature.  I'm trying to read an array of checkboxes from a form.  Is there a way to make the body parser support arrays?

**Comment by helje5** [comment]
Looking at the code, array handling should work already, the 'extended' mode seems to be on by default.

The keys need to use `[]` syntax, e.g.
```
a[]=b&a[]=c            -> [ "a": [ "b", "c" ] ]
```

Would be cool to write a test demonstrating this.

**Comment by helje5** [comment]
I added a test, seems to work fine. The way to do it is:
```swift
app.use(bodyParser.urlencoded())

app.post("/form") { req, res, next in
  let values = req.body.checkboxname as? [ String ] ?? []
  req.log("checked checkboxes:", values)
}
```

The HTML would look like:
```html
<form action="/form" ...>
  <input type="checkbox" name="mycheckbox[]" value="1">1
  <input type="checkbox" name="mycheckbox[]" value="2">2
</form>
```
