### ISSUE TITLE
Support `multipart/form-data` uploads

### ISSUE THREAD

**Issue by helje5** [Macro-swift/MacroExpress#7]
We need a body parser for `multipart/form-data` uploads, as per https://github.com/apple/swift-nio/issues/1724#issuecomment-763716401

I.e. to handle things like
```html
<form action="/upload" method="POST" enctype="multipart/form-data">
     <input type="file" id="filename" name="file" onchange="onchanged()" multiple="multiple" />
     <input type="submit" value="Upload">
</form>
```

Need to check whether there is a more official Node API for that. Generally I'd think this should stream the files to a temporary location, keep the file handles open, but unlink them - or just regular tmpfiles. The `body` structure would then have a reference to the file handles.

**Comment by helje5** [comment]
RFC: https://tools.ietf.org/html/rfc7578

Multer seems to be the default Node thing: https://www.npmjs.com/package/multer
```js
var upload = multer({ dest: 'uploads/' })
app.post('/profile',               upload.single('avatar'),       function (req, res, next) {})
app.post('/photos/upload', upload.array('photos', 12), function (req, res, next) {})
app.post('/profile',               upload.none(),                     function (req, res, next) {})

// req.files is array of `photos` files
// req.body will contain the text fields, if there were any
```

File info: filename, originalname, encoding, mimetype, size, destination (DiskStorage), filename, path, buffer

Options: 
- dest (path) or storage (xyzStorage)
- fileFilter
- limits
- preservePath

DiskStorage or MemoryStorage:
```js
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '/tmp/my-uploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})
 
var upload = multer({ storage: storage })

var storage = multer.memoryStorage()
var upload = multer({ storage: storage })
```

**Comment by helje5** [comment]
There is also Formidable: https://github.com/node-formidable/formidable

**Comment by helje5** [comment]
The `feature/multipart-formdata-1` now has an apparently working multipart/form-data parser, with quite a few tests. Only the MemoryStorage is supported so far, DiskStorage would require more async hops.

Performance doesn't seem to be too great yet, uploading a 3MB image (locally) takes 255ms in release (4s in debug), which seems a little slow for an M1 Mini. Need to check where the time gets lost.

**Comment by helje5** [comment]
Uploading my 3MB test image on M1 now takes 2ms in release (12ms in Debug), which seems quite reasonable. 100 MB take about 50ms, which also sounds OK.

What we don't have yet is DiskStorage (though it's prepared), I put that into a separate Issue #8.

The multer module is available in 0.8.0.

**Comment by Jinxiansen** [comment]
@helje5 
Thank you very much!

**Comment by pcccccc** [comment]
Hello, I am very sorry to disturb you. I haven't figured out how to receive the uploaded files.

`let app = express()

    func start() {
        app.get("/") { req, res, next in
            res.writeHead(200, [ "Content-Type": "text/html" ])
            res.write("<h1>Hello Client: \(req.url)</h1>")
            res.write("""
                <form enctype="multipart/form-data" method="post" action="/upload">
                     <input type="file" name="file">
                    <button type="submit">\("Upload")</button>
                </form>
                """)
            res.end()
        }
        
        app.post("/upload") { req, res, next in
            print(req.files) // [:]
            print(req.file) // nil
        }
        
        app.listen(1337, "0.0.0.0") { server in
            console.log("Server listening")
        }
    }`

I am very sorry to disturb you, but I really can't find the relevant information.

**Comment by helje5** [comment]
You need to inject the `multer` middleware. I've added a multer example to the Examples application: [multer middleware](https://github.com/Macro-swift/Examples/blob/417ce1c1a2ea7d4020237258a7c374ff291f7ddf/Sources/express-simple/main.swift#L68).

Like:
```swift
app.post("/upload", multer().array("file", 10)) { req, res in
    req.log.info("Got files:", req.files["file"])
    res.send("Upload complete.")
}
```

I also added more documentation to the various multer types and functions.

**Comment by pcccccc** [comment]
> You need to inject the `multer` middleware. I've added a multer example to the Examples application: [multer middleware](https://github.com/Macro-swift/Examples/blob/417ce1c1a2ea7d4020237258a7c374ff291f7ddf/Sources/express-simple/main.swift#L68).
> 
> Like:
> ```swift
> app.post("/upload", multer().array("file", 10)) { req, res in
>     req.log.info("Got files:", req.files["file"])
>     res.send("Upload complete.")
> }
> ```
> 
> I also added more documentation to the various multer types and functions.

Ok, Thank you!

**Comment by pcccccc** [comment]
> You need to inject the `multer` middleware. I've added a multer example to the Examples application: [multer middleware](https://github.com/Macro-swift/Examples/blob/417ce1c1a2ea7d4020237258a7c374ff291f7ddf/Sources/express-simple/main.swift#L68).
> 
> Like:
> 
> app.post("/upload", multer().array("file", 10)) { req, res in
>     req.log.info("Got files:", req.files["file"])
>     res.send("Upload complete.")
> }
> I also added more documentation to the various multer types and functions.

Can MacroExpress be used on iOS? When I run the demo on macOS, it works very well. When I copy the demo to the iOS project, it can run when uploading some text files, but files extension like png, zip, etc. return errors and sometimes even crash.

## steps

Copy the express-simple file from https://github.com/Macro-swift/Examples to a blank iOS project and start the server.

## log:

`2025-05-22T13:22:31+0800 error μ.http : [MacroCore] HTTP error, closing connection: read(descriptor:pointer:size:): Operation timed out (errno: 60)
2025-05-22T13:22:31+0800 error μ.http : [MacroCore] server error: read(descriptor:pointer:size:): Operation timed out (errno: 60)
2025-05-22T13:22:31+0800 error μ.console : [MacroCore] [Server:0x108bd0540] Error not handled: read(descriptor:pointer:size:): Operation timed out (errno: 60)
2025-05-22T13:22:39+0800 error μ.http : [MacroCore] HTTP error in TX 5, closing connection: read(descriptor:pointer:size:): Connection reset by peer (errno: 54)`

## crash:

![Image](https://github.com/user-attachments/assets/082441f8-aec5-4f7d-812b-c183b59f57d0)

Xcode 16.3
iPhone 14 Pro Max
iOS 18.4.1

**Comment by helje5** [comment]
Works for me on iOS, full example: https://gist.github.com/helje5/0224f2bd5f8944fc996ad486fa6ac69e

If you want, create a new issue w/ a full example project attached. I'd have a look.

My sample lacks lifecycle support, and I'm not even sure Macro currently allows tearing down a stack when the app goes to the background. Doesn't look like. Though it should be possible to add.
On iOS one should also use NIO transport services, or maybe even better: Network framework directly.

**Comment by pcccccc** [comment]
> Works for me on iOS, full example: https://gist.github.com/helje5/0224f2bd5f8944fc996ad486fa6ac69e
> 
> If you want, create a new issue w/ a full example project attached. I'd have a look.
> 
> My sample lacks lifecycle support, and I'm not even sure Macro currently allows tearing down a stack when the app goes to the background. Doesn't look like. Though it should be possible to add. On iOS one should also use NIO transport services, or maybe even better: Network framework directly.

When I avoided using "0.0.0.0" for the IP to set up the listener, it worked. Thank you 🙏.
